config/routes.rb
BaSchedule::Application.routes.draw do
  
  
  match 'imprint' => 'schedules#imprint', :as => :imprint
    
  resources :schedules do
    collection do
        get 'imprint'
        get 'subscribe'
        get 'subscription'
      end
  end

  root :to => 'schedules#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :student_id, :start_date, :end_date, :hash_string
  
  
  validates :student_id, :presence => true
  validates :hash_string, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates_date :start_date
  validates_date :end_date, :after => :start_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/schedules_controller.rb
# encoding: UTF-8
$KCODE = 'u'
class SchedulesController < ApplicationController

  layout :set_layout

  require "net/http"
  require "net/https"
  require "uri"
  require "date"
  include Icalendar

  def index
    @schedule = Schedule.new   
  end
  
  def create        
    @schedule = Schedule.new(params[:schedule])
   
    if @schedule.save
      start_date = (@schedule.start_date.beginning_of_day - 1.hour).to_i
      end_date = (@schedule.end_date.end_of_day - 1.hour + 1.second).to_i
      hash_string = params[:hash_string]
      
      uri = URI.parse("https://selfservice.campus-dual.de/room/json")
      @params = {'userid' => @schedule.student_id, 'start' => start_date, 'end' => end_date, '_' => Time.now.to_i, 'hash' => hash_string}
      http = Net::HTTP.new(uri.host, uri.port) 
      http.use_ssl = (uri.scheme == 'https')
      request = Net::HTTP::Get.new(uri.path) 
      request.set_form_data(@params)
  
      request = Net::HTTP::Get.new(uri.path+ '?' + request.body) 
      @response = http.request(request)
      
      @lessons = JSON.parse(@response.body).reject! { |lesson| lesson["start"] < start_date || lesson["start"] > end_date } unless @response.header["content-length"]
      puts @lessons
      if @lessons 
        @calendar = Calendar.new
        @calendar.custom_property("X-WR-CALNAME;VALUE=TEXT", "BA Vorlesungsplan")
        @calendar.custom_property("X-WR-TIMEZONE;VALUE=TEXT", "Europe/London")
        # @calendar.timezone do
          # timezone_id             "W. Europe Standard Time"
#         
          # daylight do
            # timezone_offset_from  "+0100"
            # timezone_offset_to    "+0200"
            # timezone_name         "CEST"
            # dtstart               "16010325T020000"
            # add_recurrence_rule   "FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3"
          # end
#         
          # standard do
            # timezone_offset_from  "+0200"
            # timezone_offset_to    "+0100"
            # timezone_name         "CET"
            # dtstart               "16011028T030000"
            # add_recurrence_rule   "FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10"
          # end
        # end        
        @lessons.each do |lesson|
          @calendar.event do
              description lesson["title"]
              dtstart     I18n.l(Time.at(lesson["start"]), :format => :ical)
              dtend       I18n.l(Time.at(lesson["end"]), :format => :ical)
              location    lesson["room"]
              summary     "#{lesson['title']} #{lesson['instructor']} #{lesson['room']}"       
          end
        end 
        @calendar_string = @calendar.to_ical
        #render :text => @calendar_string
        send_data(@calendar_string, :type => 'text/calendar; charset=UTF-8', :disposition => 'inline; filename=stundenplan.ics', :filename=>'stundenplan.ics')      
      else 
        redirect_to schedules_path, :notice => "Es wurden keine Einträge gefunden!"     
      end         
    else
      redirect_to schedules_path, :alert => "Es ist ein Fehler aufgetreten. Bitte Eingaben überprüfen!"
    end
  end    
  
  def imprint
    
  end
  
  def subscribe
    respond_to do |format|
      format.js {  }
    end
  end
  
  def subscription
    if params[:student_id]
      student_id = params[:student_id]
      hash_string = params[:hash_string]
      start_date = params[:start]#Time.now.beginning_of_day.to_i
      end_date = params[:end]#(start_date + 6.months).to_i
      now = params[:_]
      
      uri = URI.parse("https://selfservice.campus-dual.de/room/json")
      params = {'userid' => student_id, 'start' => start_date, 'end' => end_date, '_' => now, 'hash' => hash_string}
      http = Net::HTTP.new(uri.host, uri.port) 
      http.use_ssl = (uri.scheme == 'https')
      request = Net::HTTP::Get.new(uri.path) 
      request.set_form_data(params)
  
      request = Net::HTTP::Get.new(uri.path+ '?' + request.body) 
      @response = http.request(request)
      
      @lessons = JSON.parse(@response.body).reject! { |lesson| lesson["start"] < start_date || lesson["start"] > end_date } unless @response.header["content-length"]
      
      if @lessons 
        @calendar = Calendar.new        
        @calendar.custom_property("X-WR-CALNAME;VALUE=TEXT", "BA Vorlesungsplan")  
        @calendar.custom_property("X-WR-TIMEZONE;VALUE=TEXT", "Europe/London")
        # @calendar.timezone do
          # timezone_id             "W. Europe Standard Time"
#         
          # daylight do
            # timezone_offset_from  "+0100"
            # timezone_offset_to    "+0200"
            # timezone_name         "CEST"
            # dtstart               "16010325T020000"
            # add_recurrence_rule   "FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3"
          # end
#         
          # standard do
            # timezone_offset_from  "+0200"
            # timezone_offset_to    "+0100"
            # timezone_name         "CET"
            # dtstart               "16011028T030000"
            # add_recurrence_rule   "FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10"
          # end
        # end        
        @lessons.each do |lesson|
          @calendar.event do
              description lesson["title"]
              dtstart     I18n.l(Time.at(lesson["start"]), :format => :ical)
              dtend       I18n.l(Time.at(lesson["end"]), :format => :ical)
              location    lesson["room"]
              summary     "#{lesson['title']} #{lesson['instructor']} #{lesson['room']}"       
          end
        end 
        @calendar_string = @calendar.to_ical
        #render :text => @calendar_string
        send_data(@calendar_string, :type => 'text/calendar; charset=UTF-8', :disposition => 'inline; filename=stundenplan.ics', :filename=>'stundenplan.ics')      
      else 
        redirect_to schedules_path, :notice => "Es wurden keine Einträge gefunden!"     
      end             
      
    end
  end
  
  private
  
  def set_layout
    action_name == "imprint" ? "imprint" : "application"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash
   flash_messages = []
   flash.each do |type, message|
     # Skip Devise :timeout and :timedout flags
     next if type == :timeout
     next if type == :timedout
     type = :success if type == :notice
     type = :error   if type == :alert
     text = content_tag(:div, 
              content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
              message, :class => "alert fade in alert-#{type}")
     flash_messages << text if message
   end
   flash_messages.join("\n").html_safe
  end    
  
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/_fb_comments.html.erb
<div class="fb-comments" data-href="http://ba-stundenplan.herokuapp.com" data-width="700" data-num-posts="2"></div>

app/views/layouts/_fb_sdk.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1&appId=406787166069640";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>
		&copy; <%= Time.now.year %> Henrik Böttcher
		<%= link_to "Impressum", imprint_path, :class => "pull-right"%>
	</p>
</div>

app/views/layouts/_header.html.erb
<div class="masthead">
	<ul class="nav nav-pills pull-right">
		<li class="active">
			<%= link_to "Home", root_url%>
		</li>
		<li>
			<%= link_to "Kommentare", root_url << "#comments"%>
		</li>
		<li>
			<%= link_to "Kontakt", "mailto:hb@enovate.de"%>
		</li>
	</ul>
	<h3 class="muted">BA Stundenplan2CAL</h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>BA Stundenplan2CAL</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>

		<!-- Fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
		<link rel="shortcut icon" href="../assets/ico/favicon.png">
	</head>

	<body>
		<%= render "layouts/fb_sdk"%>
		<div class="container-narrow">

			<%= render "layouts/header"%>

			<hr>

			<div class="jumbotron">
				<h1>Stundenplan einfach exportieren?</h1>
				<p class="lead">
					Nach dem Motto: "Not macht erfinderisch", stellt diese App die bisher fehlende/fehlerhafte Funktion im Self-Service-Portal, den Stundenplan für Outlook, Google Calendar, iCal etc. zu exportieren, zur Verfügung.
				</p>
				<div id="main-content" class="span5">
					<%= bootstrap_flash %>
					<%= yield %>
				</div>
			</div>

			<hr>

			<div id="comments" class="row-fluid marketing">
				<div class="span12">
					<h2>Kommentare</h2>
					<br />
					<%= render "layouts/fb_comments"%>
				</div>
			</div>

			<hr>

			<%= render "layouts/footer"%>

		</div>
		<!-- /container -->
	<%= render "schedules/subscribe_modal"%>
	</body>
</html>

app/views/layouts/imprint.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>BA Stundenplan2CAL</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>

		<!-- Fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
		<link rel="shortcut icon" href="../assets/ico/favicon.png">
	</head>

	<body>
		<%= render "layouts/fb_sdk"%>
		<div class="container-narrow">

			<%= render "layouts/header"%>

			<hr>

			<div class="jumbotron imprint">
				<h1>Impressum </h1>
				<br />
				<div id="main-content" class="span7">
					<%= yield %>
				</div>
			</div>

			<hr>

			<%= render "layouts/footer"%>

		</div>
		<!-- /container -->

	</body>
</html>

app/views/schedules/_subscribe.html.erb
<form id="subscribe_form">
	<h2>Url zum Einfügen in Kalender-Software:</h2><br />
	<div class="control-group">
		<input type="text" id="subsribe_input" val="" class="span5"/>	
	</div>
</form>

app/views/schedules/_subscribe_error.html.erb
<div class="alert fade in alert-error">Es ist ein Fehler aufgetreten. Bitte Eingaben überprüfen!</div>

app/views/schedules/_subscribe_modal.html.erb
<div class="modal fade" id="subscribe_modal" style="display: none;">
    <div class="modal-header">
	    <button class="close" data-dismiss="modal">×</button>
    	<h3>Kalender Abo Url</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    	<a href="javascript:void(0);" class="btn modal_cancel">Cancel</a>
    	<a href="javascript:void(0);" class="btn btn-primary modal_submit">Submit</a>
    </div>
</div>

app/views/schedules/imprint.html.erb
<p>Henrik Böttcher<br />
Eilenburger Str. 15<br />
04808 Wurzen</p>
<h2>Kontakt:</h2>
E-Mail: hb@enovate.de</p>
<h2>Haftungsausschluss:</h2>
<p><strong>Haftung für Inhalte</strong></p>
<p>Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>
<p><strong>Haftung für Links</strong></p>
<p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>
<p><strong>Urheberrecht</strong></p>
<p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>
<p><strong>Datenschutz</strong></p>
<p>Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.</p>
<p>Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.</p>
<p>Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.</p>
<p><strong>Datenschutzerklärung für die Nutzung von Facebook-Plugins<br />
(Like-Button)</strong></p>
<p>Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert. Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder dem "Like-Button" ("Gefällt mir") auf unserer Seite. Eine Übersicht über die Facebook-Plugins finden Sie hier:<br />
<a href="http://de-de.facebook.com/policy.php" target="_blank">http://developers.facebook.com/docs/plugins/</a>.</p>
<p>Wenn Sie unsere Seiten besuchen, wird über das Plugin eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt. Facebook erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben. Wenn Sie den Facebook "Like-Button" anklicken während Sie in Ihrem Facebook-Account eingeloggt sind, können Sie die Inhalte<br />
unserer Seiten auf Ihrem Facebook-Profil verlinken. Dadurch kann Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von facebook unter <a href="http://de-de.facebook.com/policy.php" target="_blank">http://de-de.facebook.com/policy.php</a></p>
<p>Wenn Sie nicht wünschen, dass Facebook den Besuch unserer Seiten Ihrem Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem Facebook-Benutzerkonto aus.</p>
<p><strong>Datenschutzerklärung für die Nutzung von Google Analytics</strong></p>
<p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. ("Google"). Google Analytics verwendet sog. "Cookies", Textdateien, die auf Ihrem Computer gespeichert<br />
werden und die eine Analyse der Benutzung der Website durch Sie ermöglicht. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website (einschließlich Ihrer IP-Adresse) wird an einen Server von Google in den USA übertragen und dort gespeichert.</p>
<p>Google wird diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben ist oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google Inc. in Verbindung bringen.</p>
<p>Sie können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p>

app/views/schedules/index.html.erb
<%= form_for @schedule, :format => "ics", :html => { :class => 'form-horizontal' } do |f|%>
	<%= render "shared/error_messages", :target => @schedule %>
	<div class="control-group">
		<%= f.label :student_id, "Matrikelnr.", :class => 'control-label'%>
		<div class="controls">
			<%= f.text_field :student_id, :class => "span2" %>	
		</div>
	</div>
	<div class="control-group">
		<%= f.label :hash_string, :class => 'control-label' do %>
			Hash <a href="<%= url_for asset_path("BA_Stundenplan2CAL.pdf") %>"><i class="icon icon-question-sign"></i></a>
		<% end %>
		<div class="controls">
			<%= f.text_field :hash_string, :class => "span2" %>	
		</div>
	</div>
	<div class="control-group">
		<%= f.label :start_date, "Termine ab", :class => 'control-label'%>
		<div class="controls">
			<%= f.text_field :start_date, :class => "span2 datepicker" %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :end_date, "Termine bis", :class => 'control-label'%>
		<div class="controls">
			<%= f.text_field :end_date, :class => "span2 datepicker" %>
		</div>
	</div>
	<div class="control-group">
		<%= f.submit ".ics generieren", :class => "btn btn-large btn-success submit" %> <span class="or">oder</span>
		<%= link_to "Abo generieren", subscribe_schedules_path, :class => "btn btn-large btn-primary submit", :remote => true %>
	</div>		
<% end%>

app/views/schedules/subscribe.js.erb
var url;
var student_id;
var hash_string;

student_id = $("#schedule_student_id").val()
hash_string = $("#schedule_hash_string").val()
url = "http://ba-stundenplan.herokuapp.com/schedules/subscription?student_id=" + student_id + "&hash_string=" + hash_string;

if (student_id == '' || hash_string == '') {
	$("#subscribe_modal .modal-body").html("<%= escape_javascript(render "subscribe_error", :formats => [:html]) %>")
} else {
	$("#subscribe_modal .modal-body").html("<%= escape_javascript(render "subscribe", :formats => [:html]) %>");
	$("#subscribe_modal #subsribe_input").val(url);
}

$("#subscribe_modal .modal-footer").hide();
$("#subscribe_modal .form-actions").hide();
$("#subscribe_modal").modal();

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
<div id="errorExplanation" class="shadow-box yellow">    
  <strong>The form could not be processed due to the following errors:</strong>
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %>  